/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;

import static org.junit.Assert.*;

public class LibraryTest {
   @Test public void testRoll (){

   }
   @Test public void testContainsDuplicate (){

   }
   @Test public void testCalculatingAverages (){
   int [] input1 = new int[]{5,6,10,7,8};
   int [] input2 = new int[]{0,34,54,45};
   float trueOutput1 = Library.calculatingAverages(input1);
   float trueOutput2 = Library.calculatingAverages(input2);
   float expectOutput1 = 7.2f;
   float expectOutput2 = 33.25f;
              assertEquals(
                      "given an array of ints returns a float of the average",
                      expectOutput1, trueOutput1, 0 );
               assertEquals(
                       "given an array of ints returns a float of the average",
                        expectOutput2, trueOutput2, 0 );

   }
   @Test public void testArrayOfArrays (){
      int[][] weeklyMonthTemperatures = {
              {66, 64, 58, 65, 71, 57, 60},
              {57, 65, 65, 70, 72, 65, 51},
              {55, 54, 60, 53, 59, 57, 61},
              {65, 56, 55, 52, 55, 62, 57}
      };
      int [] expectOutput = {55, 54, 60, 53, 59, 57, 61};
      int [] trueOutput = Library.arrayOfArrays(weeklyMonthTemperatures);
      assertArrayEquals("given a 2d array of ints returns the array of ints with the lowest average",
              expectOutput, trueOutput);
   }

}
