/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
// worked with stephen webber on this project

import java.util.*;

public class Library {
// roll a dice n times and return an array of rolls
public static int[] roll(int n) {
int [] rollArray = new int[n];
    for (int i = 0; i < rollArray.length; i++) {
        rollArray[i] = (int) (Math.random() * 6) + 1;

    }
    return rollArray;
}

public static boolean containsDuplicates (int [] array){

}
// calculate the average of an array
public static float calculatingAverages (int[] inputArray){
    int sum = 0;
    for (int i = 0; i < inputArray.length; i++) {
        sum += inputArray[i];

    }
    float average = (float) sum/ inputArray.length;
    return average;
}
// take in a 2d array and return the array with the lowest average
public static int [] arrayOfArrays (int [][] inputArray){
    int outputArray[] = new int[inputArray[0].length];
    float averagedArray [] = new float[inputArray.length];
    System.out.println(inputArray.length);
    for (int i = 0; i < inputArray.length; i++) {
        averagedArray[i] = calculatingAverages(inputArray[i]);
    }

    float lowest = 9999;
    for (int i = 0; i < averagedArray.length; i++) {
        if(averagedArray[i] < lowest){
            lowest = averagedArray[i];
            for (int j = 0; j < inputArray[0].length; j++) {
                outputArray[j] = inputArray[i][j];
            }
        }
    }
    return outputArray;
}


}
