/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;

import java.util.ArrayList;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testRestaurantString() {
        Restaurant test = new Restaurant("test", 0, 0);
        System.out.println(test);
        assertEquals("test is a 0 star restaurant with a price rating of 0", test.toString());
    }
    @Test public void testReviewString() {
        Review test = new Review("test", "test", 1, new Restaurant("test", 2, 2));
//        System.out.println(test);
        assertEquals("test says: test and gives 1 stars", test.toString());
    }
    @Test public void testRestaurantReview(){
        Restaurant testR = new Restaurant("test", 0, 0);
        testR.addReview("body", "shay", 1);
        System.out.println(testR.reviewList.get(0));
        Review testRv = new Review("body", "shay", 1, null);
        assertEquals(testRv.toString(), testR.reviewList.get(0).toString());
    }
    @Test public void testCalcStars(){
        Restaurant testR = new Restaurant("test", 0, 0);
        testR.addReview("body", "shay", 1);
        testR.addReview("body", "shay", 2);
        testR.calcStarRating(testR.starList);
        Integer expect = 1;
        assertEquals(expect, testR.stars);


    }
}
