/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test public void testAnalyzeWeather () {
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        String expectOutput = "Never saw these temperatures: 63, 67, 68, 69, ";
        String trueOutput = App.analyzeWeather(weeklyMonthTemperatures);
        assertEquals(expectOutput, trueOutput);
    }

    @Test public void testLintJS () {

        String expectOutput = "Lines missing semicolon: 3 5 11 13 15 26 28 32 36 40 41 50 51 " +
                "59 60 61 62 64 70 71 72 73 74" + " 76 77 78 79 80 82 83 84 85 86 88 89 90 " +
                "91 92 94 95 96 97 98 99 100 101 ";
        String trueOutput = App.lintJS("C:\\Users\\The other person\\Documents\\projects\\codefellows\\401\\java-basics\\linter\\app\\src\\main\\resources\\gates.js");
        assertEquals(expectOutput, trueOutput);

    }
    @Test public void testLintJSEmpty () {

        String expectOutput = "Lines missing semicolon: ";
        String trueOutput = App.lintJS("C:\\Users\\The other person\\Documents\\projects\\codefellows\\401\\java-basics\\linter\\app\\src\\main\\resources\\empty.js");
        assertEquals(expectOutput, trueOutput);

    }
    @Test public void testLintJSOne () {

        String expectOutput = "Lines missing semicolon: 1 ";
        String trueOutput = App.lintJS("C:\\Users\\The other person\\Documents\\projects\\codefellows\\401\\java-basics\\linter\\app\\src\\main\\resources\\one.js");
        assertEquals(expectOutput, trueOutput);

    }
    @Test public void testLintJSFew () {

        String expectOutput = "Lines missing semicolon: 1 2 5 ";
        String trueOutput = App.lintJS("C:\\Users\\The other person\\Documents\\projects\\codefellows\\401\\java-basics\\linter\\app\\src\\main\\resources\\few-errors.js");
        assertEquals(expectOutput, trueOutput);

    }

}
